
name: "Podcast Generator"
author: "Alessio Cardone"
description: "Generates a feed for a podcast"
runs:
  using: "docker"
  image: "Dockerfile"
branding: 
  icon: "git-branch"
  color: "red"
inputsinputs:
  email:
    description: "The committer's email address"
    required: false
    default: ""
  name:
    description: "The committer's name"
    required: false


